name: Build package

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: ['20.x']
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          working-directory: wealthwisefrontend

      - name: Install dependencies
        run: npm install
        working-directory: wealthwisefrontend

      - name: Build project
        run: npm run build
        working-directory: wealthwisefrontend
        
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: package 
          path: ./wealthwisefrontend/dist
